[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/countdown.png"
  to = "/.netlify/functions/countdown"
  status = 200
