[build]
  functions = "api"
  publish = "."

[[redirects]]
  from = "/api/countdown.png"
  to = "/.netlify/functions/countdown"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
